gestion_formations/urls.py
# gestion_formations/urls.py

from django.urls import path
from . import views  # Importe les vues de l'application courante
from gestion_formations.views import CalendarView, SeanceCalendarPageView, SessionCreateForFormationView, SessionListView
# Définit l'espace de noms de l'application (utile si vous avez plusieurs apps avec des noms d'URL similaires)
app_name = 'gestion_formations'

urlpatterns = [

    # URL pour la page d'accueil de l'application
    # Formattion.
    path('', views.formation_list, name='formation_list'),
    path('inactive/', views.formation_inactive_list,
         name='formation_inactive_list'),
    path('formation/<int:pk>/', views.formation_detail, name='formation_detail'),
    path('formation/create/', views.formation_create, name='formation_create'),
    path('formation/<int:pk>/update/',
         views.formation_update, name='formation_update'),
    path('formation/<int:pk>/delete/',
         views.formation_delete, name='formation_delete'),

    # Sessions
    # URL pour afficher la liste de toutes les sessions
    path('sessions/', SessionListView.as_view(), name='session_list'),
    path('session/<int:pk>/', views.SessionDetailView.as_view(),
         name='session_detail'),
    path('session/ajouter/', views.SeanceCreateView.as_view(), name='session_create'),
    path('session/<int:pk>/modifier/',
         views.SessionUpdateView.as_view(), name='session_update'),
    path('session/<int:pk>/supprimer/',
         views.SessionDeleteView.as_view(), name='session_delete'),

    # Url spéciale pour créer une Session sous une Formation
    path('formation/<int:formation_pk>/session/add/',
         SessionCreateForFormationView.as_view(), name='session_add_to_formation'),


    # Séances
    path('session/<int:session_pk>/seance/ajouter/',
         views.SeanceCreateView.as_view(), name='seance_create'),
    path('session/<int:session_pk>/seance/<int:pk>/modifier/',
         views.SeanceUpdateView.as_view(), name='seance_update'),
    path('seance/<int:session_pk>/seance/<int:pk>/supprimer/',
         views.SeanceDeleteView.as_view(), name='seance_delete'),
    path('seance/<int:session_pk>/seances/<int:pk>/',
         views.SeanceDetailView.as_view(), name='seance_detail'),

    # URL pour ajouter PLUSIEURS séances à une session (vue fonctionnelle)
    path('sessions/<int:session_pk>/seances/ajouter_multiple/',
         views.ajouter_plusieurs_seances, name='seance_create_multiple'),

    # Routes pour Room (Classe)
    path('rooms/', views.RoomListView.as_view(), name='room_list'),
    path('rooms/ajouter/', views.RoomCreateView.as_view(), name='room_create'),
    path('rooms/<int:pk>/', views.RoomDetailView.as_view(), name='room_detail'),
    path('rooms/<int:pk>/modifier/',
         views.RoomUpdateView.as_view(), name='room_update'),
    path('rooms/<int:pk>/supprimer/',
         views.RoomDeleteView.as_view(), name='room_delete'),



    # calendrier
    # URL pour la vue calendrier (source de données JSON pour le frontend)
    path('calendar/data/', CalendarView.as_view(), name='calendar_data'),

    # Nouvelle URL pour la page qui affiche le calendrier interactif
    path('calendar/', SeanceCalendarPageView.as_view(),
         name='seance_calendar_page'),

    # Nous ajouterons d'autres URLs ici plus tard (détail, création, etc.)
]

gestion_pedagogique/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # URL pour la page d'accueil de l'application gestion_users
    path('', include('gestion_users.urls', namespace='gestion_users')), # Inclut les URLs de l'application gestion_users
    
    # URL pour la page d'administration de Django
    path('admin/', admin.site.urls),
    
    # Inclut les URLs de l'application gestion_formations sous le préfixe '/formations/'
    path('formations/', include('gestion_formations.urls', namespace='gestion_formations')),
    
    # Vous inclurez les URLs des autres applications ici plus tard

    path('inscriptions/', include('gestion_inscriptions.urls', namespace='gestion_inscriptions')),
    # path('notes/', include('gestion_notes.urls', namespace='gestion_notes')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_users/urls.py
# gestion_users/urls.py

from django.urls import path
# Importe les vues d'authentification de Django
from django.contrib.auth import views as auth_views
from . import views  # Importe les vues de l'application courante

app_name = 'gestion_users'

urlpatterns = [

    # --- URL POUR LA CONNEXION ---
    path('', views.custom_login_view, name='login'),
    path('logout/', views.custom_logout_view, name='logout'),

    # --- URL POUR L'INSCRIPTION ---
    path('signup/', views.signup_view, name='signup'),

    # URLs pour la réinitialisation de mot de passe (vues intégrées de Django)
    # Ces vues attendent des templates spécifiques dans le sous-répertoire 'registration'
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'), # <--- C'est le nom d'URL que {% url %} recherche !

    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),

    # path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),# Capture l'identifiant de l'utilisateur et le jeton

    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    # URL pour la page de profil de l'utilisateur connecté
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),

    # URL pour la liste des formateurs et le détail d'un formateur
    path('formateurs/', views.instructor_list_view, name='formateurs_list'),
    path('formateurs/<int:pk>/', views.instructor_detail_view,
         name='formateur_detail'),
    # URL de création de formateur pour l'administration
    path('formateurs/ajouter/', views.instructor_create_view,
         name='formateur_create'),  # Si vous gérez la création ici


]

templates/includes/_footer.html
<footer class="bg-body-tertiary text-center text-lg-start">
  {% comment %} <!-- Copyright --> {% endcomment %}
  <div class="text-center p-3" style="background-color: rgb(13, 110, 253);">
    &copy; 2025 Mon Centre de Formation. Tous droits réservés.
    <a class="text-body" href="https://CFP.com/">CFP.com</a>
  </div>
  {% comment %} <!-- Copyright --> {% endcomment %}
</footer>

templates/includes/_head.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Centre C.F.P
      {% endblock %}
    </title>

    <meta name="description"
      content="{% block description %}
        

        Gestoin de centre de formation privé


      {% endblock %}" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% block extra_head %}

    {% endblock %}
  </head>
</html>

templates/includes/_header.html
{% load static %}
{% load i18n %} 

<header>
    <div class="container">
        
        <div class="d-flex justify-content-between align-items-center"> 
           
                 
                <img src="{% static 'images/logo.png' %}" alt="Logo Mon CFP" height="40"> 

                
                <h1>  Centre CFP  </h1>
            </a>
            
    </div>
  
 
    {% if user.is_authenticated %}
            {% include 'includes/_nav.html' %} 
        {% else %}
            {% include 'includes/_nav_public.html' %} 
        {% endif %}
</header>

templates/includes/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Acceuil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_users:formateurs_list' %}">Formateurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_formations:room_list' %}">Classe</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_formations:seance_calendar_page' %}">Planning</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Note</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_formations:formation_list' %}">Formations</a>
        </li>
        {# Autres liens... #}
      </ul>

      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Bonjour, {{ user.first_name|default:user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestion_users:profile' %}">Mon Profil</a>
          </li>
          <li class="nav-item">
            <form method="post" action="{% url 'gestion_users:logout' %}" class="form-inline">
              {% csrf_token %}
              <a href="{% url 'gestion_users:logout' %}" class="nav-link text-danger"><i class="bi bi-box-arrow-right me-2">Déconnexion</i></a>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestion_users:login' %}">Connexion</a>
          </li>
          {% if not settings.SSO_ENABLED %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gestion_users:signup' %}">Inscription</a>
            </li>
          {% endif %}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/_nav_public.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavPublic" aria-controls="navbarNavPublic" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNavPublic">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Centre de Formation Privé</a> {# Lien vers la liste des formations #}
        </li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'gestion_users:login' %}">Connexion</a> {# Lien vers la page de connexion #}
        </li>

        {% if not settings.SSO_ENABLED %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestion_users:signup' %}">Inscription</a> {# Lien vers la page d'inscription #}
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/_profile_sidebar.html
{% load static %}
<div class="card shadow-sm mb-4">
  <div class="card-body text-center">
    <img src="{% if user.photo %}
        {{ user.photo.url }}
      {% else %}
        {% static 'images/default-avatar.png' %}
      {% endif %}"
      class="rounded-circle img-thumbnail mb-3"
      alt="Photo de profil"
      style="width: 100px; height: 100px; object-fit: cover;" />
    <h5 class="card-title">{{ user.get_full_name }}</h5>
    <p class="card-text text-muted small">
      <span class="badge bg-{% if user.role == 'ADMIN' %}
          
          danger

        {% elif user.role == 'INSTRUCTOR' %}
          
          info

        {% else %}
          
          success

        {% endif %}">
        {{ user.get_role_display }}
      </span>
    </p>
  </div>
  <div class="list-group list-group-flush">
    <a href="{% url 'gestion_users:profile' %}" class="list-group-item list-group-item-action {% if active_tab == 'profile' %}active{% endif %}"><i class="bi bi-person-lines-fill me-2">Vue d'ensemble</i></a>
    <a href="{% url 'gestion_users:edit_profile' %}" class="list-group-item list-group-item-action {% if active_tab == 'edit' %}active{% endif %}"><i class="bi bi-pencil-square me-2"></i> Modifier profil</a>
    {% comment %} <!-- <a href="#" class="list-group-item list-group-item-action"><i class="bi bi-lock me-2"> Changer mot de passe</i> </a> --> {% endcomment %}

    {% if user.role == 'STUDENT' %}
      <a href="#" class="list-group-item list-group-item-action"><i class="bi bi-book me-2">Mes formations</i></a>
    {% elif user.role == 'INSTRUCTOR' %}
      <a href="#" class="list-group-item list-group-item-action"><i class="bi bi-easel me-2">Mes cours</i></a>
    {% endif %}

    <a href="{% url 'gestion_users:logout' %}" class="list-group-item list-group-item-action text-danger"><i class="bi bi-box-arrow-right me-2">Déconnexion</i></a>
  </div>
</div>

templates/includes/_scripts.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

{% block extra_scripts %}

{% endblock %}